"""Add blacklist table

Revision ID: 39b435c2ceea
Revises: 857846dd0650
Create Date: 2021-09-09 11:53:34.176918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39b435c2ceea'
down_revision = '857846dd0650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jwt_blacklist',
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jwt_blacklist')
    # ### end Alembic commands ###
