"""Add isPublished field

Revision ID: 4b1c4bf74d5c
Revises: fd5553fa2114
Create Date: 2021-08-25 18:54:33.634862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b1c4bf74d5c'
down_revision = 'fd5553fa2114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('is_published', sa.Boolean(), nullable=False, server_default='f'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'is_published')
    # ### end Alembic commands ###
