"""Add index

Revision ID: 4d56e419569d
Revises: e2f8ccd27467
Create Date: 2021-08-30 16:05:09.597400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d56e419569d'
down_revision = 'e2f8ccd27467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'vacancies_idx',
        'vacancies',
        [sa.text("to_tsvector('russian', name)")],
        postgresql_using='gin'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('vacancies_idx', 'vacancies')
    # ### end Alembic commands ###
