"""Increase source field length

Revision ID: 921f6490d28e
Revises: 39b435c2ceea
Create Date: 2021-09-29 09:09:45.791689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921f6490d28e'
down_revision = '39b435c2ceea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancies', 'source', sa.String(264))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancies', 'source', sa.String(128))
    # ### end Alembic commands ###
