"""Add unique for source

Revision ID: a2892a853058
Revises: 4b1c4bf74d5c
Create Date: 2021-08-26 11:46:07.770681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2892a853058'
down_revision = '4b1c4bf74d5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'vacancies', ['source'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancies', type_='unique')
    # ### end Alembic commands ###
