"""Init vacancies table

Revision ID: b59cf3356258
Revises: 
Create Date: 2021-08-30 14:44:21.195247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b59cf3356258'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('modified_at', sa.Date(), nullable=True),
    sa.Column('name', sa.String(length=264), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('source_name', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default='f', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancies')
    # ### end Alembic commands ###
