"""Add index by generated column

Revision ID: db3d36046856
Revises: 4d56e419569d
Create Date: 2021-08-31 09:23:07.007512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db3d36046856'
down_revision = '4d56e419569d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('search_index', postgresql.TSVECTOR(), sa.Computed("to_tsvector('russian', name)", ), nullable=True))
    op.create_index('vacancies_idx_column', 'vacancies', ['search_index'], unique=False, postgresql_using='gin')
    op.drop_index('vacancies_idx', 'vacancies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('vacancies_idx_column', table_name='vacancies', postgresql_using='gin')
    op.drop_column('vacancies', 'search_index')
    # ### end Alembic commands ###
