"""default is_published is true

Revision ID: e2f8ccd27467
Revises: b59cf3356258
Create Date: 2021-08-30 15:11:53.019945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f8ccd27467'
down_revision = 'b59cf3356258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancies', 'is_published', server_default='t')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancies', 'is_published', server_default='f')
    # ### end Alembic commands ###
