export const ON_APP_ERROR = 'onAppError'
export const ON_APP_SUCCESS = 'onAppSuccess'
export const ON_OPEN_CONFIRM = 'onOpenConfirm'
export const ON_CONFIRM_RESULT = 'onConfirmresult'
export const ON_SEARCH = 'onSearch'
export const ON_PAGINATE = 'onPaginate'
export const ON_APP_LOGOUT = 'onAppLogout'
